version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    groups:
      version-updates:
        applies-to: version-updates
        patterns:
          - "*"
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "npm"
    cooldown:
      default-days: 30
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      version-updates:
        applies-to: version-updates
        patterns:
          - "*"
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "npm"
    cooldown:
      default-days: 30
    directory: "/docs"
    schedule:
      interval: "weekly"
    groups:
      version-updates:
        applies-to: version-updates
        patterns:
          - "*"
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
  - package-ecosystem: "npm"
    cooldown:
      default-days: 30
    directory: "/packages/muon"
    schedule:
      interval: "weekly"
    groups:
      version-updates:
        applies-to: version-updates
        patterns:
          - "*"
      security-updates:
        applies-to: security-updates
        patterns:
          - "*"
