name: 'BrowserStack Test'

on: workflow_dispatch

jobs:
  cypress:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSER_STACK_USERNAME }}
          access-key: ${{ secrets.BROWSER_STACK_ACCESS_KEY }}
      - run: npm ci
      - run: npm run test:cypress:browserstack
