name: "Cypress_BrowserStack_Test"

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: browserstack/github-actions/setup-env@master
        with:
          username: ${{ secrets.BROWSER_STACK_USERNAME }}
          access-key: ${{ secrets.BROWSER_STACK_ACCESS_KEY }}
      - uses: bahmutov/npm-install@v1
      - run: npm run test:cypress:browserstack
        timeout-minutes: 10

      - name: Ensure BrowserStack Local tunnel is stopped
        if: always()
        run: npx browserstack-cypress stop --local-identifier CypressLocalConnection1
