name: Deploy Ember example

on: [pull_request]

jobs:
  ember-deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: cd examples/ember-app && npm install && npm run build-muon && npm run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: c3a8d8374aef6f7792fab25e95e12d0e
          projectName: 'muon-ember'
          directory: 'examples/ember-app/dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}