name: Deploy Ember example

on: [pull_request]

jobs:
  ember-deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: cd examples/ember-app && npm install && npm run build-muon && npm run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@f0a1cd58cd66095dee69bfa18fa5efd1dde93bca # v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: c3a8d8374aef6f7792fab25e95e12d0e
          projectName: 'muon-ember'
          directory: 'examples/ember-app/dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
