name: 'Percy Snapshots'

on: workflow_dispatch

jobs:
  percy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: bahmutov/npm-install@v1
      - run: npm run test:percy
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
