name: Publish NPM experimental

on:
  push:
    branches:
      - main

jobs:
  publish-experimental:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm version prerelease --git-tag-version=false --preid=experimental-"$(git show -s --format=%h)" --workspace=@muon/library 
      - run: npm publish --workspace=@muon/library --access public --tag experimental
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}