name: Publish NPM stable

on:
  release:
    types: [released]

jobs:
  publish-stable:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish --workspace=@muonic/muon --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}