name: Deploy Storybook main

on:
  push:
    branches:
      - main

jobs:
  storybook-deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - uses: bahmutov/npm-install@v1
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          buildScriptName: build
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}