name: Tests

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: bahmutov/npm-install@v1
      - run: npm run lint

  browserstack:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: bahmutov/npm-install@v1
      - run: npm run test:browserstack
    env:
        BROWSER_STACK_USERNAME: ${{ secrets.BROWSER_STACK_USERNAME }}
        BROWSER_STACK_ACCESS_KEY: ${{ secrets.BROWSER_STACK_ACCESS_KEY }}

  testing:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: bahmutov/npm-install@v1
      - run: npx playwright install
      - run: npx playwright install-deps
      - run: npm run test
      - uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: packages/library/coverage/lcov-report/*
          if-no-files-found: warn
  
  scripts-testing:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: bahmutov/npm-install@v1
      - run: npm run test:scripts
      - uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: packages/library/coverage/scripts-coverage/*
          if-no-files-found: warn

  storybook-accessibility:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: bahmutov/npm-install@v1
      - run: npx playwright install
      - run: npx playwright install-deps
      - run: npm run test:axe
