name: Tests

on: [pull_request]

jobs:
  installer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: zip package.zip ./* -r
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: package.zip
          retention-days: 1
  lint:
    needs: installer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - uses: actions/download-artifact@v3
        with:
          name: package
      - run: unzip package.zip
      - run: npm run lint

  browserstack:
    needs: installer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - uses: actions/download-artifact@v3
        with:
          name: package
      - run: unzip package.zip
      - run: npm run test:browserstack
    env:
        BROWSER_STACK_USERNAME: ${{ secrets.BROWSER_STACK_USERNAME }}
        BROWSER_STACK_ACCESS_KEY: ${{ secrets.BROWSER_STACK_ACCESS_KEY }}

  testing:
    needs: installer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - uses: actions/download-artifact@v3
        with:
          name: package
      - run: unzip package.zip
      - run: npx playwright install-deps
      - run: npm run test
      - uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: packages/library/coverage/lcov-report/*
          if-no-files-found: warn

  storybook-accessibility:
    needs: installer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - uses: actions/download-artifact@v3
        with:
          name: package
      - run: unzip package.zip
      - run: npm run test:axe
