name: Tests

on: [pull_request]

jobs:
  installer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: zip node_modules.zip ./node_modules/* -r
      - uses: actions/upload-artifact@v3
        with:
          name: node_modules
          path: node_modules.zip
          retention-days: 1
  lint:
    needs: installer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - uses: actions/download-artifact@v3
        with:
          name: node_modules
      - run: unzip node_modules.zip -d ./node_modules
      - run: npm run lint

  browserstack:
    needs: installer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - uses: actions/download-artifact@v3
        with:
          name: node_modules
      - run: unzip node_modules.zip -d ./node_modules
      - run: npm run test:browserstack
    env:
        BROWSER_STACK_USERNAME: ${{ secrets.BROWSER_STACK_USERNAME }}
        BROWSER_STACK_ACCESS_KEY: ${{ secrets.BROWSER_STACK_ACCESS_KEY }}

  testing:
    needs: installer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - uses: actions/download-artifact@v3
        with:
          name: node_modules
      - run: unzip node_modules.zip -d ./node_modules
      - run: npx playwright install-deps
      - run: npm run test
      - uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: packages/library/coverage/lcov-report/*
          if-no-files-found: warn

  storybook-accessibility:
    needs: installer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - uses: actions/download-artifact@v3
        with:
          name: node_modules
      - run: unzip node_modules.zip -d ./node_modules
      - run: npm run test:axe
