name: Tests

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run lint

  browserstack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run test:browserstack
    env:
        BROWSER_STACK_USERNAME: ${{ secrets.BROWSER_STACK_USERNAME }}
        BROWSER_STACK_ACCESS_KEY: ${{ secrets.BROWSER_STACK_ACCESS_KEY }}

  testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npx playwright install-deps
      - run: npm run test
      - uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: packages/library/coverage/lcov-report/*
          if-no-files-found: warn
    env:
      PUPPETEER_PRODUCT: 'firefox'
